---
title: "CONTRIBUTING"
author: Angeline Tillmanns
date: December 10, 2020
output: md_document
---

## How to contribute
Government employees, public and members of the private sector are encouraged to contribute to the repository by **forking and submitting a pull request**. 

(If you are new to GitHub, you might start with a [basic tutorial](https://help.github.com/articles/set-up-git) and  check out a more detailed guide to [pull requests](https://help.github.com/articles/using-pull-requests/).)

Pull requests will be evaluated by the repository guardians on a schedule and if deemed beneficial will be committed to the master.

All contributors retain the original copyright to their stuff, but by contributing to this project, you grant a world-wide, royalty-free, perpetual, irrevocable, non-exclusive, transferable license to all users **under the terms of the license under which this project is distributed.**

**To track copyright, please use the following:** 

**New code file:** At the top of the file, please ensure copyright and year is attributed to collaborator and assign the Apache 2.0 license

**Major addition to code file:** “Copyright 2018-2024 Province of British Columbia” and Apache 2.0 remains as a header and either the second collaborator is added if there are changes throughout the code or copyright is listed for specific lines of code.  So it could read:

Copyright 2018-2024 Province of British Columbia
Copyright 2024 Collaborator
Apache 2.0 License

Or 

Copyright 2018-2024 Province of British Columbia
Copyright 2024 Collaborator Lines 200-500
Apache 2.0 License

**Minor changes:**  If there are small changes to the code throughout the file then it may be easiest to keep these files as Copyright 2018-2024 Province of British Columbia.  
However, the contribution will be tracked through GitHub.
