---
title: "Frequently Asked Questions"
author: "ssdtools Team"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
bibliography: references.bib
# csl: style.csl
mainfont: Arial
mathfont: Courier
latex_engine: MathJax
output: rmarkdown::html_vignette
#output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Frequently Asked Questions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4
)
```

## How can I...

### ... plot the model averaged fit and the individual fits?

```{r, fig.width = 6, fig.height = 4}
library(ssdtools)

dist <- ssd_fit_dists(ssddata::ccme_boron)
ssd_plot_cdf(dist, average = NA)
```

### ... fit distributions to multiple groups such taxa and/or chemicals?

An elegant approach using some tidyverse packages is demonstrated below.

```{r, message=FALSE}
library(ssddata)
library(ssdtools)
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)

boron_preds <- nest(ccme_boron, data = c(Chemical, Species, Conc, Units)) %>%
  mutate(
    Fit = map(data, ssd_fit_dists, dists = "lnorm"),
    Prediction = map(Fit, predict)
  ) %>%
  unnest(Prediction)
```

The resultant data and predictions can then be plotted as follows.
```{r, fig.width = 6, fig.height = 4}
ssd_plot(ccme_boron, boron_preds, xlab = "Concentration (mg/L)", ci = FALSE) +
  facet_wrap(~Group)
```

### ... include mathematical expressions in the xlabel when using `ssd_plot()`?

```{r, fig.width = 6, fig.height = 4}
library(ggplot2)
library(latex2exp)

ssd_plot(ssddata::ccme_boron, ssdtools::boron_pred, label = "Species", shape = "Group") +
  scale_x_continuous(TeX("Boron $(\\mu g$/L)$"), breaks = c(1, 10, 100, 1000, 10000))
```

<!-- ### ... generate bootstrap samples in parallel? -->

<!-- Set `future::plan()`.  -->
<!-- For example: -->
<!-- ```{r, eval=FALSE} -->
<!-- future::multisession(workers = 2) -->
<!-- hc5 <- ssd_hc(fits, ci = TRUE) -->
<!-- ``` -->

<!-- To perform bootstrapping for each distribution in parallel register the future backend -->
<!-- and then select the evaluation strategy. -->
<!-- ```{r, eval=FALSE} -->
<!-- doFuture::registerDoFuture() -->
<!-- future::plan(future::multisession) -->

<!-- set.seed(99) -->
<!-- boron_pred <- predict(fits, ci = TRUE) -->
<!-- ``` -->

<!-- Bootstrapping is computationally intensive.  -->
<!-- To bootstrap for each distribution in parallel register the future back-end -->
<!-- and then select the evaluation strategy. -->

<!-- ```{r, eval = FALSE} -->
<!-- doFuture::registerDoFuture() -->
<!-- future::plan(future::multisession) -->
<!-- ``` -->

<div id="refs"></div>

```{r, results = "asis", echo = FALSE}
cat(ssd_licensing_md())
```
