#    Copyright 2015 Province of British Columbia
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

test_that("hp fitdist", {
  hp <- ssd_hp(boron_lnorm, numeric(0)) 
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, numeric(0))
  expect_equal(hp$est, numeric(0)) 
  expect_equal(hp$se, numeric(0))
  expect_equal(hp$lcl, numeric(0))
  expect_equal(hp$ucl, numeric(0))
  expect_equal(hp$dist, character(0))
  
  hp <- ssd_hp(boron_lnorm, NA_real_, average = FALSE)
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_equal(hp$dist, "lnorm")
  expect_identical(hp$conc, NA_real_)
  expect_equal(hp$est, NA_real_)
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_)
  expect_equal(hp$ucl, NA_real_)
  expect_equal(ssd_hp(boron_lnorm, 1)$est, 1.95430302556687)
  
  hp <- ssd_hp(boron_lnorm, 0) 
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_equal(hp$dist, "average")
  expect_identical(hp$conc, 0) 
  expect_equal(hp$est, 0)
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_)
  expect_equal(hp$ucl, NA_real_)
  
  hp <- ssd_hp(boron_lnorm, -1, average = FALSE)
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_equal(hp$dist, "lnorm")
  expect_identical(hp$conc, -1)
  expect_equal(hp$est, 0)
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_) 
  expect_equal(hp$ucl, NA_real_)
  
  hp <- ssd_hp(boron_lnorm, -Inf)
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_equal(hp$dist, "average")
  expect_identical(hp$conc, -Inf)
  expect_equal(hp$est, 0) 
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_)
  expect_equal(hp$ucl, NA_real_)
  
  hp <- ssd_hp(boron_lnorm, Inf, average = FALSE)
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_equal(hp$dist, "lnorm")
  expect_identical(hp$conc, Inf)
  expect_equal(hp$est, 100)
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_)
  expect_equal(hp$ucl, NA_real_)

  expect_equal(ssd_hp(boron_lnorm, c(1, 30))$est, c(1.95430302556687, 75.0549005516345))
})

test_that("hp fitdist cis", {
  set.seed(10)
  hp <- ssd_hp(boron_lnorm, 1, ci = TRUE, nboot = 10)
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, 1)
  expect_equal(hp$est, 1.95430302556687) 
  expect_equal(hp$se, 1.35655179053438) 
  expect_equal(hp$lcl, 0.753456291493635) 
  expect_equal(hp$ucl, 4.40213333315012) 
  expect_equal(hp$dist, "average")
                                                                                                          
  set.seed(10)
  hp <- ssd_hp(boron_lnorm, c(1, 30), ci = TRUE, nboot = 10)
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, c(1, 30))
  expect_equal(hp$dist, c("average", "average"))
  expect_equal(hp$est, c(1.95430302556687, 75.0549005516345))
  expect_equal(hp$se, c(1.35655179053438, 5.11894303490242))
  expect_equal(hp$lcl, c(0.753456291493635, 71.4201716163438))
  expect_equal(hp$ucl, c(4.40213333315012, 87.0527043686382))
})

test_that("hp fitdists with no dists", {
  x <- list()
  class(x) <- c("fitdists")
  hp <- ssd_hp(x, numeric(0))
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, numeric(0))
  expect_equal(hp$est, numeric(0))
  expect_equal(hp$se, numeric(0))
  expect_equal(hp$lcl, numeric(0))
  expect_equal(hp$ucl, numeric(0))
  expect_equal(hp$dist, character(0))
  
  hp <- ssd_hp(x, 2)
  expect_is(hp, c("tbl_df", "tbl", "data.frame"))
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, numeric(0))
  expect_equal(hp$est, numeric(0))
  expect_equal(hp$se, numeric(0))
  expect_equal(hp$lcl, numeric(0))
  expect_equal(hp$ucl, numeric(0))
  expect_equal(hp$dist, character(0))
})

test_that("hp fitdists", {
  hp <- ssd_hp(boron_dists, 1)
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, 1)
  expect_equal(hp$est, 3.66685732661861)
  expect_equal(hp$se, NA_real_)
  expect_equal(hp$lcl, NA_real_)
  expect_equal(hp$ucl, NA_real_)
  expect_equal(hp$dist, "average")
                                                                                                                                      
  hp <- ssd_hp(boron_dists, c(0, 1, 30, Inf))
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, c(0, 1, 30, Inf))
  expect_equal(hp$est, c(0, 3.66685732661861, 72.9017755369416, 100))
  expect_equal(hp$se, c(NA_real_, NA_real_, NA_real_, NA_real_))
  expect_equal(hp$lcl, c(NA_real_, NA_real_, NA_real_, NA_real_))
  expect_equal(hp$ucl, c(NA_real_, NA_real_, NA_real_, NA_real_))
  expect_equal(hp$dist, c("average", "average", "average", "average")) 
})

test_that("hp fitdists cis", {
  set.seed(10)
  hp <- ssd_hp(boron_dists, 1, ci = TRUE, nboot = 10)
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, 1)
  expect_equal(hp$est, 3.66685732661861)
  expect_equal(hp$se, 1.74868222529788)
  expect_equal(hp$lcl, 1.50422454139995)
  expect_equal(hp$ucl, 6.15380996129333)
  expect_equal(hp$dist, "average") 
  
  set.seed(10)
  hp <- ssd_hp(boron_dists, c(0, 1, 30, Inf), ci = TRUE, nboot = 10)
  expect_is(hp, "tbl_df")
  expect_identical(colnames(hp), c("dist", "conc", "est", "se", "lcl", "ucl"))
  expect_identical(hp$conc, c(0, 1, 30, Inf))
  expect_equal(hp$est, c(0, 3.66685732661861, 72.9017755369416, 100))
  expect_equal(hp$se, c(0, 1.74868222529788, 8.02368234572414, 0))
  expect_equal(hp$lcl, c(0, 1.50422454139995, 60.9396881989019, 100))
  expect_equal(hp$ucl, c(0, 6.15380996129333, 83.0798543477598, 100))
  expect_equal(hp$dist, c("average",  "average", "average", "average"))
})
