# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_ssd <- function(x, shape, scale) {
    .Call('_ssdtools_dgamma_ssd', PACKAGE = 'ssdtools', x, shape, scale)
}

pgamma_ssd <- function(q, shape, scale) {
    .Call('_ssdtools_pgamma_ssd', PACKAGE = 'ssdtools', q, shape, scale)
}

qgamma_ssd <- function(p, shape, scale) {
    .Call('_ssdtools_qgamma_ssd', PACKAGE = 'ssdtools', p, shape, scale)
}

rgamma_ssd <- function(n, shape, scale) {
    .Call('_ssdtools_rgamma_ssd', PACKAGE = 'ssdtools', n, shape, scale)
}

dgompertz_ssd <- function(x, location, shape) {
    .Call('_ssdtools_dgompertz_ssd', PACKAGE = 'ssdtools', x, location, shape)
}

pgompertz_ssd <- function(q, location, shape) {
    .Call('_ssdtools_pgompertz_ssd', PACKAGE = 'ssdtools', q, location, shape)
}

qgompertz_ssd <- function(p, location, shape) {
    .Call('_ssdtools_qgompertz_ssd', PACKAGE = 'ssdtools', p, location, shape)
}

rgompertz_ssd <- function(n, location, shape) {
    .Call('_ssdtools_rgompertz_ssd', PACKAGE = 'ssdtools', n, location, shape)
}

dgumbel_ssd <- function(x, location, scale) {
    .Call('_ssdtools_dgumbel_ssd', PACKAGE = 'ssdtools', x, location, scale)
}

pgumbel_ssd <- function(q, location, scale) {
    .Call('_ssdtools_pgumbel_ssd', PACKAGE = 'ssdtools', q, location, scale)
}

qgumbel_ssd <- function(p, location, scale) {
    .Call('_ssdtools_qgumbel_ssd', PACKAGE = 'ssdtools', p, location, scale)
}

rgumbel_ssd <- function(n, location, scale) {
    .Call('_ssdtools_rgumbel_ssd', PACKAGE = 'ssdtools', n, location, scale)
}

dlnorm_ssd <- function(x, meanlog, sdlog) {
    .Call('_ssdtools_dlnorm_ssd', PACKAGE = 'ssdtools', x, meanlog, sdlog)
}

plnorm_ssd <- function(q, meanlog, sdlog) {
    .Call('_ssdtools_plnorm_ssd', PACKAGE = 'ssdtools', q, meanlog, sdlog)
}

qlnorm_ssd <- function(p, meanlog, sdlog) {
    .Call('_ssdtools_qlnorm_ssd', PACKAGE = 'ssdtools', p, meanlog, sdlog)
}

rlnorm_ssd <- function(n, meanlog, sdlog) {
    .Call('_ssdtools_rlnorm_ssd', PACKAGE = 'ssdtools', n, meanlog, sdlog)
}

dlogis_ssd <- function(x, location, scale) {
    .Call('_ssdtools_dlogis_ssd', PACKAGE = 'ssdtools', x, location, scale)
}

plogis_ssd <- function(q, location, scale) {
    .Call('_ssdtools_plogis_ssd', PACKAGE = 'ssdtools', q, location, scale)
}

qlogis_ssd <- function(p, location, scale) {
    .Call('_ssdtools_qlogis_ssd', PACKAGE = 'ssdtools', p, location, scale)
}

rlogis_ssd <- function(n, location, scale) {
    .Call('_ssdtools_rlogis_ssd', PACKAGE = 'ssdtools', n, location, scale)
}

dweibull_ssd <- function(x, shape, scale) {
    .Call('_ssdtools_dweibull_ssd', PACKAGE = 'ssdtools', x, shape, scale)
}

pweibull_ssd <- function(q, shape, scale) {
    .Call('_ssdtools_pweibull_ssd', PACKAGE = 'ssdtools', q, shape, scale)
}

qweibull_ssd <- function(p, shape, scale) {
    .Call('_ssdtools_qweibull_ssd', PACKAGE = 'ssdtools', p, shape, scale)
}

rweibull_ssd <- function(n, shape, scale) {
    .Call('_ssdtools_rweibull_ssd', PACKAGE = 'ssdtools', n, shape, scale)
}

