# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dburrXII_ <- function(x, shape1 = 1, shape2 = 1, scale = 2.718282, log_ = FALSE) {
    .Call('_ssdtools_dburrXII_', PACKAGE = 'ssdtools', x, shape1, shape2, scale, log_)
}

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('_ssdtools_timesTwo', PACKAGE = 'ssdtools', x)
}

