# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

plogis_ssd <- function(q, location, scale) {
    .Call(`_ssdtools_plogis_ssd`, q, location, scale)
}

qlogis_ssd <- function(p, location, scale) {
    .Call(`_ssdtools_qlogis_ssd`, p, location, scale)
}

rlogis_ssd <- function(n, location, scale) {
    .Call(`_ssdtools_rlogis_ssd`, n, location, scale)
}

pweibull_ssd <- function(q, shape, scale) {
    .Call(`_ssdtools_pweibull_ssd`, q, shape, scale)
}

qweibull_ssd <- function(p, shape, scale) {
    .Call(`_ssdtools_qweibull_ssd`, p, shape, scale)
}

rweibull_ssd <- function(n, shape, scale) {
    .Call(`_ssdtools_rweibull_ssd`, n, shape, scale)
}

