library(ssdtools)
set.seed(42)
fit <- ssd_fit_dists(ssddata::ccme_boron)
ssd_gof(fit)
hc <- ssd_hc(fit, ci = TRUE)
print(hc)
autoplot(fit)
ggplot2::ggsave("paper/autoplot.png", device = "png", width = 6, height = 4)
predictions <- ssdtools::predict(fit, ci = TRUE)
ssd_plot(ssddata::ccme_boron, predictions, shape = "Group")
ggplot2::ggsave("paper/ssd_plot.png", device = "png", width = 6, height = 4)
